import UIImage from "./Images/Courses/UX-UI.jpg";
import WebDevelopment from "./Images/Courses/Web-Development.jpg";
import Modeling3D from "./Images/Courses/3D-Modeling.jpg";
import GraphicDesign from "./Images/Courses/Graphic-Design.jpg";
import UXResearch from "./Images/Courses/UX-Research.jpg";
import PublicSpeaking from "./Images/Courses/Public-Speaking.jpg";
import MobileDevelopment from "./Images/Courses/Mobile-Development.jpg";

export const CourseData = [
  {
    title: "Interpersonal Skills - Work Better With Others!",
    label: "UX/UI Design",
    team: "Tanah Air Team",
    prevPrice: 640,
    discount: 384,
    rating: 3,
    category: "Art & Design",
    image: UIImage,
    id: 0,
    cssId: "design",
  },
  {
    title: "How To Become An Expert Web Developer",
    label: "Web Development",
    team: "Tanah Air Team",
    prevPrice: 680,
    discount: 520,
    rating: 5,
    category: "Development",
    image: WebDevelopment,
    id: 1,
    cssId: "development",
  },
  {
    title: "User Experience Design Essentials",
    label: "UX Research",
    team: "Tanah Air Team",
    prevPrice: 850,
    discount: 740,
    rating: 4,
    category: "Design",
    image: UXResearch,
    id: 2,
    cssId: "design",
  },
  {
    title: "Creating 3D Models in Blender",
    label: "3D Design",
    team: "Tanah Air Team",
    prevPrice: 760,
    discount: 620,
    rating: 5,
    category: "Art & Design",
    image: Modeling3D,
    id: 3,
    cssId: "design",
  },
  {
    title: "Mastering public presentations",
    label: "Public Speaking",
    team: "Tanah Air Team",
    prevPrice: 310,
    discount: 190,
    rating: 4,
    category: "Business",
    image: PublicSpeaking,
    id: 4,
    cssId: "business",
  },
  {
    title: "How To Become An Expert Mobile Developer",
    label: "App Development",
    team: "Tanah Air Team",
    prevPrice: 820,
    discount: 785,
    rating: 5,
    category: "Development",
    image: MobileDevelopment,
    id: 5,
    cssId: "development",
  },
  {
    title: "Creating 3D Models in Maya",
    label: "3D Design",
    team: "Tanah Air Team",
    prevPrice: 745,
    discount: 595,
    rating: 4,
    category: "Art & Design",
    image: Modeling3D,
    id: 6,
    cssId: "design",
  },
  {
    title: "How To Become An Experienced Graphic Designer",
    label: "Graphic Design",
    team: "Tanah Air Team",
    prevPrice: 400,
    discount: 305,
    rating: 4,
    category: "Art & Design",
    image: GraphicDesign,
    id: 7,
    cssId: "design",
  },
  {
    title: "C# Beginner Course",
    label: "Programming language",
    team: "Tanah Air Team",
    prevPrice: 950,
    discount: 520,
    rating: 5,
    category: "Development",
    image: WebDevelopment,
    id: 8,
    cssId: "development",
  },
  {
    title: "C# Advanced Course",
    label: "Programming language",
    team: "Tanah Air Team",
    prevPrice: 950,
    discount: 520,
    rating: 5,
    category: "Development",
    image: MobileDevelopment,
    id: 9,
    cssId: "development",
  },
  {
    title: "Unity fundamentals",
    label: "Game Development",
    team: "Tanah Air Team",
    prevPrice: 950,
    discount: 520,
    rating: 5,
    category: "Development",
    image: MobileDevelopment,
    id: 10,
    cssId: "development",
  },
  {
    title: "Figma fundamentals",
    label: "Art & Design",
    team: "Tanah Air Team",
    prevPrice: 640,
    discount: 384,
    rating: 3,
    category: "Art & Design",
    image: UIImage,
    id: 11,
    cssId: "design",
  },
  {
    title: "PHP Fundamentals",
    label: "Web Development",
    team: "Tanah Air Team",
    prevPrice: 680,
    discount: 520,
    rating: 5,
    category: "Development",
    image: WebDevelopment,
    id: 12,
    cssId: "development",
  },
  {
    title: "Mastering Adobe XD",
    label: "UI Design",
    team: "Tanah Air Team",
    prevPrice: 850,
    discount: 740,
    rating: 4,
    category: "Art & Design",
    image: UXResearch,
    id: 13,
    cssId: "design",
  },
  {
    title: "Creating 3D Models in AutoCAD",
    label: "3D Design",
    team: "Tanah Air Team",
    prevPrice: 760,
    discount: 620,
    rating: 5,
    category: "Art & Design",
    image: Modeling3D,
    id: 14,
    cssId: "design",
  },
  {
    title: "Mastering public presentations",
    label: "Public Speaking",
    team: "Tanah Air Team",
    prevPrice: 310,
    discount: 190,
    rating: 4,
    category: "Business",
    image: PublicSpeaking,
    id: 15,
    cssId: "business",
  },
  {
    title: "Vue.js for begginers",
    label: "App Development",
    team: "Tanah Air Team",
    prevPrice: 820,
    discount: 785,
    rating: 5,
    category: "Development",
    image: MobileDevelopment,
    id: 16,
    cssId: "development",
  },
  {
    title: "Adobe Illustrator and Photoshop fundamentals",
    label: "Graphic Design",
    team: "Tanah Air Team",
    prevPrice: 745,
    discount: 595,
    rating: 4,
    category: "Art & Design",
    image: Modeling3D,
    id: 17,
    cssId: "design",
  },
  {
    title: "How To Become An Experienced Graphic Designer",
    label: "Graphic Design",
    team: "Tanah Air Team",
    prevPrice: 400,
    discount: 305,
    rating: 4,
    category: "Art & Design",
    image: GraphicDesign,
    id: 18,
    cssId: "design",
  },
  {
    title: "Business fundamentals",
    label: "Business",
    team: "Tanah Air Team",
    prevPrice: 950,
    discount: 520,
    rating: 5,
    category: "Business",
    image: WebDevelopment,
    id: 19,
    cssId: "business",
  },
  {
    title: "Excel fundamentals",
    label: "Business",
    team: "Tanah Air Team",
    prevPrice: 950,
    discount: 520,
    rating: 5,
    category: "Business",
    image: MobileDevelopment,
    id: 20,
    cssId: "business",
  },
  {
    title: "30 Main Steps of Start Up",
    label: "Business",
    team: "Tanah Air Team",
    prevPrice: 950,
    discount: 520,
    rating: 5,
    category: "Business",
    image: MobileDevelopment,
    id: 21,
    cssId: "business",
  },
  {
    title: "Business relations",
    label: "Business",
    team: "Tanah Air Team",
    prevPrice: 640,
    discount: 384,
    rating: 3,
    category: "Business",
    image: UIImage,
    id: 22,
    cssId: "business",
  },
  {
    title: "How To Become A Successful CEO",
    label: "Business",
    team: "Tanah Air Team",
    prevPrice: 680,
    discount: 520,
    rating: 5,
    category: "Business",
    image: WebDevelopment,
    id: 23,
    cssId: "business",
  },
  {
    title: "Business Intermediate Course",
    label: "Business",
    team: "Tanah Air Team",
    prevPrice: 850,
    discount: 740,
    rating: 4,
    category: "Business",
    image: UXResearch,
    id: 24,
    cssId: "business",
  },
  {
    title: "Business Expert Course",
    label: "Business",
    team: "Tanah Air Team",
    prevPrice: 760,
    discount: 620,
    rating: 5,
    category: "Business",
    image: Modeling3D,
    id: 25,
    cssId: "business",
  },
  {
    title: "100 Rules of Business",
    label: "Business",
    team: "Tanah Air Team",
    prevPrice: 310,
    discount: 190,
    rating: 4,
    category: "Business",
    image: PublicSpeaking,
    id: 26,
    cssId: "business",
  },
  {
    title: "How To Write Appealing Content",
    label: "Marketing",
    team: "Tanah Air Team",
    prevPrice: 820,
    discount: 785,
    rating: 5,
    category: "Marketing",
    image: MobileDevelopment,
    id: 27,
    cssId: "marketing",
  },
  {
    title: "Marketing fundamentals",
    label: "Marketing",
    team: "Tanah Air Team",
    prevPrice: 745,
    discount: 595,
    rating: 4,
    category: "Marketing",
    image: Modeling3D,
    id: 28,
    cssId: "marketing",
  },
  {
    title: "Marketing Intermediate Course",
    label: "Marketing",
    team: "Tanah Air Team",
    prevPrice: 400,
    discount: 305,
    rating: 4,
    category: "Marketing",
    image: GraphicDesign,
    id: 29,
    cssId: "marketing",
  },
  {
    title: "Marketing Expert Course",
    label: "Marketing",
    team: "Tanah Air Team",
    prevPrice: 950,
    discount: 520,
    rating: 5,
    category: "Marketing",
    image: WebDevelopment,
    id: 30,
    cssId: "marketing",
  },
  {
    title: "Marketing - Working With Your Dream Business",
    label: "Marketing",
    team: "Tanah Air Team",
    prevPrice: 950,
    discount: 520,
    rating: 5,
    category: "Marketing",
    image: MobileDevelopment,
    id: 31,
    cssId: "marketing",
  },
  {
    title: "Creating Content With Canva",
    label: "Marketing",
    team: "Tanah Air Team",
    prevPrice: 950,
    discount: 520,
    rating: 5,
    category: "Marketing",
    image: MobileDevelopment,
    id: 32,
    cssId: "marketing",
  },
  {
    title: "Photoshop fundamentals",
    label: "Marketing",
    team: "Tanah Air Team",
    prevPrice: 640,
    discount: 384,
    rating: 3,
    category: "Marketing",
    image: UIImage,
    id: 33,
    cssId: "marketing",
  },
  {
    title: "How To Become An Expert Web Developer",
    label: "Web Development",
    team: "Tanah Air Team",
    prevPrice: 680,
    discount: 520,
    rating: 5,
    category: "Development",
    image: WebDevelopment,
    id: 34,
    cssId: "development",
  },
  {
    title: "User Experience Design Essentials",
    label: "UX Research",
    team: "Tanah Air Team",
    prevPrice: 850,
    discount: 740,
    rating: 4,
    category: "Marketing",
    image: UXResearch,
    id: 35,
    cssId: "marketing",
  },
  {
    title: "Creating 3D Models in Blender",
    label: "3D Design",
    team: "Tanah Air Team",
    prevPrice: 760,
    discount: 620,
    rating: 5,
    category: "Art & Design",
    image: Modeling3D,
    id: 36,
    cssId: "design",
  },
  {
    title: "Mastering public presentations",
    label: "Public Speaking",
    team: "Tanah Air Team",
    prevPrice: 310,
    discount: 190,
    rating: 4,
    category: "Business",
    image: PublicSpeaking,
    id: 37,
    cssId: "business",
  },
  {
    title: "How To Become An Expert Mobile Developer",
    label: "App Development",
    team: "Tanah Air Team",
    prevPrice: 820,
    discount: 785,
    rating: 5,
    category: "Development",
    image: MobileDevelopment,
    id: 38,
    cssId: "development",
  },
  {
    title: "Creating 3D Models in Maya",
    label: "3D Design",
    team: "Tanah Air Team",
    prevPrice: 745,
    discount: 595,
    rating: 4,
    category: "Art & Design",
    image: Modeling3D,
    id: 39,
    cssId: "design",
  },
  {
    title: "How To Become An Experienced Graphic Designer",
    label: "Graphic Design",
    team: "Tanah Air Team",
    prevPrice: 400,
    discount: 305,
    rating: 4,
    category: "Art & Design",
    image: GraphicDesign,
    id: 40,
    cssId: "design",
  },
  {
    title: "C# Beginner Course",
    label: "Programming language",
    team: "Tanah Air Team",
    prevPrice: 950,
    discount: 520,
    rating: 5,
    category: "Development",
    image: WebDevelopment,
    id: 41,
    cssId: "development",
  },
  {
    title: "C# Advanced Course",
    label: "Programming language",
    team: "Tanah Air Team",
    prevPrice: 950,
    discount: 520,
    rating: 5,
    category: "Development",
    image: MobileDevelopment,
    id: 42,
    cssId: "development",
  },
  {
    title: "Unity fundamentals",
    label: "Game Development",
    team: "Tanah Air Team",
    prevPrice: 950,
    discount: 520,
    rating: 5,
    category: "Development",
    image: MobileDevelopment,
    id: 43,
    cssId: "development",
  },
];
